-- Screen = {}
-- Screen.WIDTH = 800
-- Screen.HEIGHT = 600
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
METER_SIZE = 64
GRAVITY = 9.8
WIND = 0

GRAVITY = GRAVITY * METER_SIZE
WIND = WIND * METER_SIZE

PLAYER_1 = 0
PLAYER_2 = 1